# Whether to install zsh and neovim plugins
nvimplugins = false
zshplugins = false
# Whether to enable colemak rebinds
colemak = true

# Which shell to use (bash, zsh, or fish)
shell = "bash"
# Whether to enable zsh completion
zshcomp = false
# Whether to enable zsh abbeviations
zshabbr = false

# Whether to automatically start tmux or zellij. DO NOT SET BOTH TO TRUE
# NOTE: When setting this option you should also set sudo to forward the $TMUX
# environmental variable when starting an interactive shell.
tmux = false
zellij = true

# Which EDITOR to use
editor = "nvim"

# What app should be used for PAGER (less or moor)
pager = "less"
# What app should be used for MANPAGER (less, most, or nvim)
manpager = "less"

# Whether to download my preferred fonts
fonts = false
# What font size to use
fontsize = "12"
# Font to use for terminal emulators
termfont = "0xProto Nerd Font Mono"
# Font to use for desktop
deskfont = "CodeNewRoman Nerd Font Mono"
# Font to use for everything else
normfont = "Cantarell"

# Whether to use a desktop
graphical = false
# Whether to use sway
sway = false
# Which terminal emulator to use
term = "foot"
